#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
/** @var Container $container */
$container = require __DIR__ . '/core/bootstrap.php';

use Core\Config\ConfigLoader;
use Core\DI\Container;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$routePath = __DIR__ . '/route/route.yaml';
$config = ConfigLoader::load($routePath);

if (!isset($config['commands'])) {
    echo("No commands defined\n");
    exit(1);
}
$commandsConfig = $config['commands'];

$commandName = $input->getFirstArgument();

if (!$commandName) {
    echo("Ошибка: Не указана команда.\n");
    exit(1);
}
$className = null;
foreach ($commandsConfig as $commandConfig) {
    if ($commandConfig['name'] === $commandName) {
        $className = $commandConfig['class'];
        break;
    }
}
if (!isset($className)) {
    echo "Команда {$commandName} не найдена.\n";
}
if ($className) {
    try {
        $command = new $className($input, $container->get(\Core\Logger\AppLoggerInterface::class));
    } catch (Throwable $e) {
        echo "Не удалось инициализировать комманду: {$commandName}.\n";
    }
}
exit(0);
