logger:
  channel: default
  production: false
channels:
  default:
    path: application
    file:
      name: application
    daily: true
    days: 7
  console:
    path: console
    file:
      name: console
    daily: true
    days: 7
  kafka-work:
    path: kafka
    file:
      name: kafka-work
    daily: true
    days: 7
  rabbitmq-work:
    path: rabbitmq
    file:
      name: rabbitmq-work
    daily: true
    days: 7
  message-handler:
    path: messages
    file:
      name: message-handler
    daily: true
    days: 7
  notifications:
    path: notifications
    file:
      name: notifications
    daily: true
    days: 7