logger:
  channel: default
  production: false
channels:
  default:
    path: application
    file:
      name: application
    daily: true
    days: 7
  controllers:
    path: controllers
    file:
      name: controllers
    daily: true
    days: 7